name: TrustyAI Explainability - CI
on: [ push, pull_request ]
jobs:
  event-connect-build:
    env:
      MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
      MAVEN_ARGS: "-nsu -fae -e"
    concurrency:
      group: pull_request-${{ github.event_name }}-${{ github.head_ref }}-${{ matrix.os }}-${{ matrix.java-version }}-${{ matrix.maven-version }}
      cancel-in-progress: true
    timeout-minutes: 45
    strategy:
      matrix:
        # configure with [ 'ubuntu-latest', 'windows-latest' ] to enable Windows builds
        include:
          - {os: ubuntu-latest, shell: bash }
        #  - {os: windows-latest, shell: cmd }
        java-version: [ 11, 17 ]
        maven-version: [ '3.6.3', '3.8.6' ]
      fail-fast: false
    # https://docs.github.com/en/actions/using-jobs/setting-default-values-for-jobs#setting-default-shell-and-working-directory
    defaults:
      run:
        shell: ${{ matrix.shell }} {0}
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - Java ${{ matrix.java-version }} - Maven ${{ matrix.maven-version }}- Build and Test
    steps:
      - name: Disk space report before modification
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          echo "Available storage:"
          df -h
      # Inspired to maximize-build-space action https://github.com/easimon/maximize-build-space
      - name: Free disk space (remove dotnet, android and haskell)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
      - name: Disk space report after modification
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          echo "Available storage:"
          df -h
      - name: Support long paths
        # set to use cmd for windows not pwsh
        if: ${{ matrix.os == 'windows-latest' }}
        run: git config --system core.longpaths true
      - name: Set up JDK + Maven version
        # include actions/checkout, actions/setup-java, actions/cache, see https://github.com/s4u/setup-maven-action/blob/main/action.yml
        uses: s4u/setup-maven-action@v1.7.0
        with:
          java-version: ${{ matrix.java-version }}
          maven-version: ${{ matrix.maven-version }}
      - name: Run mvn package
        run: mvn package -Dmaven.test.skip=true -Dformatter.skip=true
      - name: Validate Formatting
        # execute formatting validation only on Ubuntu to avoid issues with CR LF
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: mvn net.revelc.code.formatter:formatter-maven-plugin:validate
      - name: Run Test Suite
        run: mvn verify
      - name: Check Test Report without publishing
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1.0.10
        with:
          skip_publishing: true
          check_name: Test Results
          fail_on_test_failures: true
          fail_if_no_tests: false
